module.exports = [
    'Art',
    'Anthropomorphism',
    'Biography & Autobiography',
    'Body, Mind & Spirit',
    'Business & Economics',
    'Botany',
    'British',
    'Computers',
    'Comics & Graphic Novels',
    'Cosmic physics',
    'Education',
    'Family & Relationships',
    'Fiction',
    'Foreign Language Study',
    'Gardening',
    'History',
    'Inventions',
    'Juvenile Nonfiction',
    'Language Arts & Disciplines',
    'Law',
    'Literary Criticism',
    'Love',
    'Mathematics',
    'Medical',
    'Nature',
    'Philosophy',
    'Political Science',
    'Religion',
    'Science',
    'Social Science',
    'Technology & Engineering',
    'Young Adult Fiction'
];